### ISSUE TITLE
No departure sound after patch

### ISSUE THREAD

**Issue by gergles** [GMMan/dengo-plug-and-play-chimes-patch#1]
Thanks for getting this set up! I got the patch to apply successfully (and a backup was made) to my unit. The logfile reported "dgf: OK".

After the patch, I no longer have any departure noise at all - the beep that was there is gone, but none of the 'correct' melodies play.

I attempted to run the patch again but got the expected result of it erroring out telling me my checksum mismatched.

I hacked on the script a little to manually copy the files a second time but I still have no departure sounds. (See the [attached log.txt](https://github.com/GMMan/dengo-plug-and-play-chimes-patch/files/5890083/log.txt) for directory listings where the chimes should go.) 

I'd appreciate any help in figuring out the issue. If you'd like my backup (MD5 `57ac39e3408887006108a17e20291c3f`), let me know.

The contents of `installed.md5` are `9224481050509458f3244b42c872a629`.

**Comment by GMMan** [comment]
I think I might have diffed my patch on a file that was already partially patched, which means not all of the patches were applied. I have updated the patch, so run it with the revert flag and power cycle and it should install the correct patch.

**Comment by arnauos** [comment]
I've modified the install script to restore just the binary and then reapply your new diff to it (https://gist.github.com/arnauos/8e8da8ef55bfd7e4c7833d4dedb98dcd)

I can confirm the previous patch did create a different hashed binary:

```
original: 8674a2f48f119150042efb141d4eca051f04ee8a
previous patch: bb14aa91157d921c7c871d8ea2718f44537445d4
new patch: cc3f7cac9b3c36d6c05dd8893068e2e4ce198b99
```

However, in my case I didn't notice any issues with the original patch 😰

**Comment by gergles** [comment]
I downloaded the latest commit `c3d04df`, erased the drive except for the Chimes directory, then copied the script files over. I deleted `backup_required`, added the `revert` file, then powercycled the unit twice.

I still don't have departure sound. The log file says:

```
dgf: OK

dgf_patched: OK
```

`dgf_patched.sha1` contains `cc3f7cac9b3c36d6c05dd8893068e2e4ce198b99 *dgf_patched`.

I'm happy to help with any other scripts to determine if there's file issues or if there's any other logging we can get after. I'm preparing the flash drive on a Mac - are the filenames case sensitive, perhaps?

**Comment by GMMan** [comment]
Could you put the following in the script:
```sh
find /root/Data/ -type f -exec sha1sum {} \;  | sort -k2 > /mnt/sums.txt
find /root/Data/ -type f -exec ls -l {} \; > /mnt/files.txt
```

Maybe you have some slightly different files somewhere. For reference I have the following:
- [sums.txt](https://github.com/GMMan/dengo-plug-and-play-chimes-patch/files/5896404/sums.txt)
- [files.txt](https://github.com/GMMan/dengo-plug-and-play-chimes-patch/files/5896405/files.txt) (note this needs to be sorted by last column if you're going to do a diff).

**Comment by gergles** [comment]
This is an egg-on-my-face situation – my audio files had different sums and were in fact, not the same as the ones from the install.

Replacing them with the correct audio files works as expected. Thanks so much for your help!
